[package]
name = "rdclient"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
gstreamer = "0.23"
gstreamer-app = "0.23"
evdev = "0.13"
wayland-client = "0.31.15"
wayland-protocols = { version = "0.32.13", features = ["client", "staging"] }
moonlight-sys = { path = "moonlight-sys" }
openssl = "0.10"
reqwest = { version = "0.12", default-features = false, features = ["native-tls"] }
directories = "5"
khronos-egl = { version = "6", features = ["static"] }
wayland-egl = "0.32"
glow = "0.14"
